[build]
builder = "nixpacks"
buildCommand = "cd backend && npm install --omit=dev"

[deploy]
startCommand = "cd backend && npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure" 